app-type: "WASM-IPFS-Serverless-WORKER"

# The network model of HTTP handle ,NetPoll(gin) RAWEPOLL(fiber)
net-model: "NETPOLL"

# Process inflow traffic network configuration
NetWork:
  bind-network: "TCP" # Network transport layer type: TCP | UDP 
  protocol-type: "HTTP" # Application layer network protocol: HTTP | RESP | QUIC
  bind-address: "127.0.0.1:28080" # Network listening address

# Runtime debug option
debug:
  enable: false # Enable or disable runtime debugging
  pprof-bind-addr: "127.0.0.1:19090" # Address to bind the pprof server

# Configuration for loading WASM modules from local files
wasm-modules-files:
  enable: false # Enable or disable loading WASM modules from local files
  path:
    - "hello.wasm" # Path to the WASM module file

# Configuration for loading WASM modules from IPFS
wasm-modules-ipfs:
  enable: false # Enable or disable loading WASM modules from IPFS
  lassie-net:
    scheme: "http" # Protocol scheme for the Filecoin-Lassie network
    host: "x.x.x.x" # Host address for the Filecoin-Lassie network
    port: xxxx # Port number for the Filecoin-Lassie network
  cids:
    - "QmeDsaLTc8dAfPrQ5duC4j5KqPdGbcinEo5htDqSgU8u8Z" # Content Identifier (CID) for the WASM module in IPFS
